language: python

sudo: required

services:
  - docker

env:
  matrix:
    - ROLE=forwarder
    - ROLE=aggregator

script:
  - cd ./$ROLE
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    printf '%s' "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$ROLE-$TRAVIS_TAG" release
    fi
  fi

after_failure: make logs
